### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by TigerAB1** [med-air/Client-DP-FL#1]
您好，我最近也在学习客户端层面的差分隐私，但是我发现我加上高斯噪声之后，精度反而提高了你有没有遇到过这种情况？

**Comment by MeiruiJiang** [comment]
您好，如果您讨论的是对客户端的模型加噪声，一般情况下应该会导致精度受损。
不太清楚您具体如何添加的噪声，我目前没有遇到过这种情况。
